config/routes.rb
VerboiceXForms::Application.routes.draw do

  resources :forms do
    resources :recordings, :controller => :form_recordings do
      member do
        post '/', :action => :save
      end
    end
    member do
      get 'xml'
    end
  end
  resources :endpoints do
    resources :recordings, :controller => :endpoint_recordings do
      member do
        post '/', :action => :save
      end
    end
  end
  resources :calls

  match '/:guid' => 'endpoints#enqueue', :guid => /[0-9a-f]{32}/, :as => 'enqueue'

  scope '/verboice' do
    match '/callback'
    match '/status'
  end

  match '/' => redirect('/forms')

  get 'terms_and_conditions', :to => redirect('/')
end

app/models/endpoint.rb
class Endpoint < ActiveRecord::Base
  has_many :forms, :dependent => :destroy
  has_many :calls, :through => :forms

  validates_presence_of :name

  before_create :generate_guid

  include Recording

  def generate_guid
    self.guid ||= Digest::MD5.hexdigest(Time.now.to_f.to_s)
  end

  def post_results call
    if callback_url
      RestClient.post callback_url, {:xml_submission_file => call.data, :multipart => true}
    end
  end
  handle_asynchronously :post_results

  def with_time_zone
    old_time_zone = Time.zone
    Time.zone = time_zone
    yield
  ensure
    Time.zone = old_time_zone
  end

  def recordings_path
    File.join Rails.root, 'data', 'endpoint', self.id.to_s
  end
end

app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController
  respond_to :html
  
  def edit
    @schedule = schedules.select{|q| q.name == endpoint.schedule}.first
  end

  def create
    endpoint.save
    respond_with endpoint, :location => endpoints_path
  end

  def update
    endpoint.save
    respond_with endpoint, :location => endpoints_path
  end

  def destroy
    endpoint.destroy
    respond_with endpoint
  end

  def enqueue
    endpoint = Endpoint.find_by_guid(params[:guid])
    
    form = endpoint.forms.where(:external_id => params[:form_id]).first

    data = form.xform.model_instance
    values = {}
    form.mappings.keys.each do |key|
      values[key] = params[key]
    end
    form.map_to_xml(data, values)
    
    time = endpoint.with_time_zone do
      Time.zone.parse("#{params[:call_date]} #{params[:call_time]}").try(:utc)
    end

    Call.create! :phone => params[:phone_number], :form => form, :data => data.to_s, :not_before => time
    render :text => endpoint.name
  end  
end

app/views/endpoints/_form.haml
= form_for(endpoint) do |f|
  = errors_for endpoint

  = f.label :name
  %br
  = f.text_field :name, :class => "w60"
  %br
  %br

  = f.label :callback_url, "Callback URL"
  %br
  = f.text_field :callback_url, :class => "w60"
  %br
  %br

  = f.label :schedule
  %br
  = f.collection_select :schedule, schedules, :name, :name, {:prompt => 'Select one'}, {:class => "w30"}
  %br
  %br

  = f.label :channel
  %br
  = f.select :channel, channels, {:prompt => 'Select one'}
  %br
  %br

  = f.label :time_zone, "Time Zone"
  %br
  = f.time_zone_select :time_zone, nil, {:default => "UTC"}, :class => "w30"
  %br
  %br

  = f.label :retry_count
  %br
  = f.select :retry_count, 0..9
  %br
  %br

  %hr

  .bottom-actions
    %button.white Save
    = link_to 'Discard', endpoints_path, :class => "tgrey"
    - unless endpoint.new_record?
      .right
        = link_to "Delete this Endpoint", endpoint_path(endpoint), :method => :delete, :confirm => "Are you sure you want to delete this endpoint? All forms associated with this endpoint will be deleted too.", :class => 'fdelete'

app/views/endpoints/_header.haml
%h1= endpoint.name.capitalize
%ul.tabs.top
  = tab 'Settings', edit_endpoint_path(endpoint)
  = tab 'Recordings', endpoint_recordings_path(endpoint)
.tabsline
  = yield

app/views/endpoints/edit.haml
= render :layout => 'header' do
  = render 'form'

app/views/endpoints/index.haml
%h1 Endpoints
.tablewrapp.w60
  %table.GralTable.TwoColumn.CleanTable
    %tr
      %th My Endpoints
      %th
    - endpoints.each do |endpoint|
      %tr.link{'data-url' => edit_endpoint_path(endpoint)}
        %td
          = endpoint.name
          %span.grey= "(#{enqueue_url(:guid => endpoint.guid)})"
        %td
          %button.farrow{:type => "button"}
    %tr.add.link{'data-url' => new_endpoint_path}
      %td Create Endpoint
      %td
        %button.cadd{:type => "button"}
%br
%br
%br

app/views/endpoints/new.haml
%h1 New Endpoint
= render 'form'