config/routes.rb
VerboiceXForms::Application.routes.draw do

  resources :forms do
    resources :recordings, :controller => :form_recordings do
      member do
        post '/', :action => :save
      end
    end
    member do
      get 'xml'
    end
  end
  resources :endpoints do
    resources :recordings, :controller => :endpoint_recordings do
      member do
        post '/', :action => :save
      end
    end
  end
  resources :calls

  match '/:guid' => 'endpoints#enqueue', :guid => /[0-9a-f]{32}/, :as => 'enqueue'

  scope '/verboice' do
    match '/callback'
    match '/status'
  end

  match '/' => redirect('/forms')

  get 'terms_and_conditions', :to => redirect('/')
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  respond_to :html
  
  before_filter :read_xml_file, :only => [:create, :update]

  def create
    if form.save
      flash[:notice] = "Form successfully created"
      redirect_to forms_path
    else
      respond_with form
    end
  end

  def update
    if form.save
      flash[:notice] = "Form successfully updated"
      redirect_to forms_path
    else
      respond_with form
    end
  end

  def destroy
    form.destroy
    flash[:notice] = "Form successfully deleted"
    respond_with form
  end
  
  def xml
    render :xml => form.xml
  end
  
  private
  
  def read_xml_file
    file = params[:form][:xml_file]
    if file
      params[:form].delete :xml_file
      form.xml = file.read
      form.file_name = file.original_filename
      form.file_date = Time.now.utc
    end
  end
  
end

app/views/forms/_form.haml
= content_for :head do
  = javascript_include_tag 'form'

= form_for(form) do |f|
  = errors_for form

  = f.label :name
  %br
  = f.text_field :name, :class => "w60"
  %br
  %br

  = f.label :endpoint
  %br
  = f.collection_select :endpoint_id, Endpoint.all, :id, :name, {:prompt => 'Select one'}, {:class => "w30"}
  %br
  %br

  = f.label :external_id, "External Identifier"
  %br
  = f.text_field :external_id, :class => "w30"
  %br
  %br


  = f.label :xml_file, "Source"
  - if form.file_date.present?
    %span.grey= "uploaded #{time_ago_in_words form.file_date} ago"
  - if form.file_name.present?
    %span= link_to "(#{form.file_name})", xml_form_path(form)
  %br
  = f.file_field :xml_file
  %br
  %br

  = f.label :mappings
  %br
  = f.hidden_field :mappings_str
  %ul#mappings.mclist.w40
    %li#mapping_template
      %span.arrowgrey
      %input.ux-mclist{:type => "text"}
      %button.mclist-remove
    %li#add_mapping
      %input#add_mapping_key.arrowinput{:type => "text", :placeholder => "Field name"}
      %input#add_mapping_value.ux-text{:type => "text", :placeholder => "Field source's xPath"}
      %button.mclist-add
  %br

  %hr

  .bottom-actions
    %button#submit_form.white Save
    = link_to 'Discard', forms_path, :class => "tgrey"
    - unless form.new_record?
      .right
        = link_to "Delete this form", form_path(form), :method => :delete, :confirm => "Are you sure you want to delete this form?", :class => 'fdelete'

app/views/forms/_header.haml
%h1= form.name.capitalize

%ul.tabs.top
  = tab 'Settings', edit_form_path(form)
  = tab 'Recordings', form_recordings_path(form)
.tabsline
  = yield

app/views/forms/edit.haml
= render :layout => 'forms/header' do
  = render 'form', :form => form

app/views/forms/index.haml
%h1 Forms
.tablewrapp.w60
  %table.GralTable.TwoColumn.CleanTable
    %tr
      %th My Forms
      %th
    - forms.each do |form|
      %tr.link{'data-url' => edit_form_path(form)}
        %td= form.name
        %td
          %a.farrow{:type => "button"}
    %tr.add.link{'data-url' => new_form_path}
      %td Create Form
      %td
        %button.cadd{:type => "button"}
%br
%br
%br

app/views/forms/new.haml
%h1 New form
= render 'form', :form => form